- name: Firewalld - stopping service
  service:
    name: firewalld
    state: stopped

- name: Firewalld - create service manifest directory
  file:
    path: "{{ firewalld_svc_path }}"
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: Firewalld - add zookeeper service manifest
  template:
    src: "{{ item }}.j2"
    dest: "{{ firewalld_svc_path }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - zookeeper.xml

- name: Firewalld - add zookeeper service to rule set
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: yes
    state: enabled
    offline: yes
  loop:
    - zookeeper

- name: Firewalld - starting service
  service:
    name: firewalld
    state: started